const borderPokemonType = {
  fire: "border-[3px] border-orange-500",
  grass: "border-[3px] border-green-700",
  normal: "border-[3px] border-pink-700",
  fighting: "border-[3px] border-amber-700",
  flying: "border-[3px] border-blue-500",
  poison: "border-[3px] border-purple-700",
  ground: "border-[3px] border-amber-500",
  rock: "border-[3px] border-stone-500",
  bug: "border-[3px] border-red-300",
  ghost: "border-[3px] border-purple-500",
  steel: "border-[3px] border-teal-600",
  water: "border-[3px] border-blue-700",
  electric: "border-[3px] border-yellow-500",
  psychic: "border-[3px] border-gray-500",
  ice: "border-[3px] border-teal-300",
  dragon: "border-[3px] border-amber-700",
  dark: "border-[3px] border-purple-400",
  fairy: "border-[3px] border-pink-500",
  unknown: "border-[3px] border-gray-700",
  shadow: "border-[3px] border-blue-950",
};
const bgPokemonType = {
  fire: "bg-gradient-to-b from-orange-600 via-orange-300 to-white",
  grass: "bg-gradient-to-b from-green-900 via-green-600 to-white",
  normal: "bg-gradient-to-b from-pink-700 via-pink-400 to-withe",
  fighting: "bg-gradient-to-b from-amber-700 via-amber-400 to-white",
  flying: "bg-gradient-to-b from-blue-500 via-blue-200 to-white",
  poison: "bg-gradient-to-b from-purple-700 via-purple-400 to-white-200",
  ground: "bg-gradient-to-b from-amber-500 via-amber-200 to-white",
  rock: "bg-gradient-to-b from-stone-700 via-stone-400 to-white",
  bug: "bg-gradient-to-b from-amber-900 via-red-300 to-white",
  ghost: "bg-gradient-to-b from-gray-700 via-purple-400 to-white",
  steel: "bg-gradient-to-b from-teal-700 via-teal-400 to-white",
  water: "bg-gradient-to-b from-blue-700 via-blue-400 to-white",
  electric: "bg-gradient-to-b from-yellow-700 via-yellow-400 to-withe",
  psychic: "bg-gradient-to-b from-gray-700 via-gray-400 to-white",
  ice: "bg-gradient-to-b from-teal-400 via-teal-100 to-white",
  dragon: "bg-gradient-to-b from-yellow-600 via-rose-300 to-white",
  dark: "bg-gradient-to-b from-slate-900 via-purple-900 to-slate-100",
  fairy: "bg-gradient-to-b from-red-200 via-red-300 to-white",
  unknown: "bg-gradient-to-b from-gray-700 to-gray-200",
  shadow: "bg-gradient-to-b from-blue-950 to-blue-200",
};

export { bgPokemonType, borderPokemonType };
